import java.util.Date;
import java.util.Calendar;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

/*--------------INFO--------------------
		Author: D Kalsi (909298)
		Updated by: D Connolly (2128770)
----------------------------------------*/

public class Booking {
	
	private static ArrayList<Booking> bookings = new ArrayList<Booking>();
	private int numGuest;
	private String date;
	private String time;
	private String id;
	private String custID;
	private int duration;
	private boolean approved;
	private boolean confirmation;
	
	private static int count = 0;
	/*
	//Formats the date and time to day/month/year and hour:minutes 
	private SimpleDateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm");
		*/
		
	public Booking(int customerID, int guest, String date, String time) {
		this.id = "B" + count;
		custID = "C" + customerID;
		numGuest = guest;
		this.date = date;
		this.time = time;
		duration = 1;
		approved = false;
		confirmation = true;
		System.out.println("Thanks, your booking ID is: " + id);
		count++;
	}
	/*
	@Override
	public String toString() {
		return "ID: " + id + "\nBooking start: " + startDate.getTime() + "\nBooking end: " + 
	endDate.getTime() + "\nDuration: " + duration + " hour\nApproved: " + approved ;
	}
	*/
	public String getID() {
		return id;
	}
	
	public int getGuestNum() {
		return numGuest;
	}
	
	public int getDuration() {
		return duration;
	}
	
	public boolean getConfirmation() {
		return confirmation;
	}
	/*
	public void setGuestNUm(int newGuest) {
		numGuest = newGuest;
	}
	
	public void extendDuration(int newTime) {
		duration = newTime;
		endDate.add(Calendar.HOUR_OF_DAY, duration);
	}
	*/
	public void approve() {
		approved = true;
	}
	
	public void cancel(int bookingID) {
		confirmation = false;
	}
	
	public static void addBook(Booking b) {
		bookings.add(b);
	}
	
	public static Booking getBooking(int i) {
		return bookings.get(i);
	}
	
	
	/*
	//Method to parse a String to a Calendar variable to give the date
	private Calendar toDate(String date) {
		Calendar dateTime = Calendar.getInstance();
		
		//This was generated by eclipse, will have to test properly and probably tweak it
		try {
			dateTime.setTime(df.parse(date));
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return dateTime;
	}
		
	//Sets the initial end time of the booking
	private Calendar end(Calendar start) {
		Calendar endTime = start;
		
		endTime.add(Calendar.HOUR_OF_DAY, duration);
		
		return endTime;
	}
	*/
	/*
	public static void main(String[] args) {
		Date date = new Date();
		Booking b1 = new Booking(10928, 4, "22/03/22 12:00");
		
		System.out.println(b1.toString());
		System.out.println();
		
		b1.extendDuration(3);
		b1.approve();
		System.out.println(b1.toString());
	}
*/
	
}